### ISSUE TITLE
curl may be aliased by Invoke-WebRequest on Windows

### ISSUE THREAD

**Issue by MostAwesomeDude** [jyn514/cohost-backup#5]
Paraphrasing private conversation with [remeranAuthor](https://cohost.org/remeranAuthor/), `curl` might be an alias to `Invoke-WebRequest` on Windows machines. They indicate that they had to change `curl` to `curl.exe` to fix this, and wanted me to reach out to let you know. I don't have a Windows machine handy to test this myself though.

**Comment by jyn514** [comment]
that's already handled here: https://github.com/jyn514/cohost-backup/blob/c23a3513b9dc1e576cedbb5811ff527ebaaaeaaa/extract.ps1#L39

is she running into an error? can she post it here?

i wonder if i need to have it twice in a row after all :pensive: i tested this in a VM but windows always surprises me at its capacity to be buggy https://stackoverflow.com/a/24743647/7669110

**Comment by jyn514** [comment]
pushed a change that should hopefully fix it; can you try again and see if it helps? https://github.com/jyn514/cohost-backup/commit/13eebb2a7040e91210bfaae76c55a7a09e5b7721

**Comment by remeranAuthor** [comment]
I was indeed running into an error previously, and it looks like putting in that line twice did indeed fix it on my windows machine. Thank you!
